<?php


return [


  /*
  |--------------------------------------------------------------------------
  | Prefixes prepended to route URI and route name.
  |--------------------------------------------------------------------------
  |*/

  'api-uri-prefix' => 'api',
  'api-route-name-prefix' => 'api',

  /*
  |--------------------------------------------------------------------------
  | Route Recursion Depth
  |--------------------------------------------------------------------------
  |
  | Determines how deeply to inspect Eloquent Model relations
  | to expose sub-resource routes.
  |
  | For example if we have users, which have many posts, which have many comments,
  | which have many responses, a depth of 1 will expose...
  |
  |   api/users/i/posts
  |
  | But NOT...
  |
  |   api/users/i/posts/j/comments
  |
  | A depth 3 on the other hand, will expose the full relation lineage...
  |
  |   api/users/i/posts/j/comments/k/responses
  |
  */

  'recursion-depth' => 6,

  /*
  |--------------------------------------------------------------------------
  | Auth-User Access Rules
  |--------------------------------------------------------------------------
  |
  | The root of the resource path represented by a URI endpoint, must be
  | associated with the auth user via one of the rules configured here.
  |
  | A rule is an array where key 'user-id-property' specifies which property
  | is references the owner's user id. Optionally the 'model' key, limits
  | the rule to specific model type (if omitted the rule applies to any
  | model).
  |
  */

  'access-rules' => [

    // If the root resource  User-based resource, we expect
    // the user id passed in the route to be equal to the logged in user
    ['user-id-property' => 'id', 'model' => '\\App\\Model\\User'],

    // Further, if we encounter a 'user_id' property on any resource,
    // we will use it to accept or reject access.
    ['user-id-property' => 'user_id']

  ],


  /*
  |--------------------------------------------------------------------------
  | Models directory
  |--------------------------------------------------------------------------
  |
  | Location of Eloquent Model subclasses, relative to app/, where we will
  | inspect for relationship declarations. Will recurse subdirectories.
  |
  */
  'models-directory' => 'Models',

  /*
  |--------------------------------------------------------------------------
  | Relations JS file output location
  |--------------------------------------------------------------------------
  |
  | Location of output generated by autocrud:inspect-relations command
  |
  | Model relations are expressed as a JS object, in the form required by the
  | artisanwebworks/autocrud-vuex NPM package
  |
  | Location relative to base directory.
  |
  */
  'relations-output' => 'resources/js/relations.js'


];
